### ISSUE TITLE
Adding support for setting Ketra bulb color.

### ISSUE THREAD

**Issue by eclair4151** [gurumitts/pylutron-caseta#153]
Hello, I have a QSX Processor with some Ketra bulbs. They work great just changing the level, but I'd love to add support for being able to change the color on them as well. Ideally, which can then be integrated into Home Assistant for full color support.

I already have the leap commands needed in order to set the color of the Ketra bulbs.

 I see code here to handle the ketra lamp,
https://github.com/gurumitts/pylutron-caseta/blob/0c327110670fa61b5adba0aa9484007403ae77b7/pylutron_caseta/smartbridge.py#L312

Do you have any suggestions how I should implement this? I was thinking of just adding an optional parameter to the set value method which could then take in a color. Thoughts? or I could make a new method all together which supports taking in a color and value.

**Comment by cbw** [comment]
Hi @eclair4151, I have't looked at this code in a while – I have Ketra bulbs as well and this was on my eventual to-do list. Won't have time to dig in for a couple weeks, but if you need someone to help test, happy to help!

**Comment by eclair4151** [comment]
No problem! I have Ketra bulbs as well to test. I was planning on writing the code and raising a PR myself, just curious if you recommend I add an optional parameter to the current set value method for color or just define a new method all together :)

**Comment by cbw** [comment]
At first glance, I think an optional parameter is probably the most straightforward/logical way to approach it. Since they can either do full color or a specified color temperature, would be great to accommodate either.

Do the LEAP commands you've found also include being able to change it back from a specific color/color temp to warm dim mode?

**Comment by eclair4151** [comment]
Heres my initial take at what it would look like. Tested and works great for my bulbs. Still need to finish the tests and handle the responses, but let me know if you think is a good direction. One thing you'll notice is, I marked the value as optional as well because you can set the color of the Ketra bulb without adjusting the value. 

https://github.com/gurumitts/pylutron-caseta/compare/dev...eclair4151:pylutron-caseta:dev


 ```
ketra_device_id = "XYZ"

  color_value = WarmCoolColorValue(2700)
  # color_value = FullColorValue(145, 25, 255)
  # color_value = WarmDimmingColorValue(True)
  # color_value = VibrancyColorValue(50)

  await bridge.set_value(ketra_device_id,  color_value=color_value)
```

**Comment by eclair4151** [comment]
Just raised a PR for this. take a look whenever you get a chance and let me know if you have any feedback
#154

**Comment by eclair4151** [comment]
Still got a bunch of work to do to make it production ready but already have a POC of this working with Home Assistant as well.

https://photos.app.goo.gl/VAziwYKXhbo8fo4z7

**Comment by eclair4151** [comment]
Corresponding Home Assistant feature branch that pairs to this PR #154 

https://github.com/eclair4151/home-assistant-core/tree/ketra_lumaris_color_support

Once you checkout that branch, youll need to manually install the new version of pylutron-caseta as well.
Open a terminal in your Home Assistant Core, or the terminal tab in vscode docker, and run

pip uninstall pylutron-caseta    
pip install git+https://github.com/eclair4151/pylutron-caseta.git@dev

**Comment by eclair4151** [comment]
@cbw Any initial thoughts :) would love some feedback just to make sure it looks like I'm going in the right direction. The PR is pretty much done besides some tests I need to update, but haven't been able to get in contact with the repo maintainers to get some feedback. I know you guys are all super busy, so I don't want to be pushy at all! Just excited to get this new functionality into home assistant so I can start using it with my automations 😁.

**Comment by mdonoughe** [comment]
Fixed in #154

**Comment by mdonoughe** [comment]
https://pypi.org/project/pylutron-caseta/0.19.0/

**Comment by eclair4151** [comment]
Awesome, thanks again for the help! I'll get the Home Assistant PR raised, and hopefully we can all start using the new feature soon 😁

**Comment by kneath** [comment]
First of all — thank you for all this support! I've recently moved into my Ketra filled new construction and everything has been working great with my HA install. I didn't want to open a new issue since I sort of don't know where to ask this question, but this feels appropriate enough. Please let me know if there's a better forum for these types of questions — QSX/Ketra.

I have two "natural shows" programmed into my house — one for normal (cooler), one for relax (warmer). I've been able to keep the natural show temperature shift in HA scenes by only changing brightness, but I can't switch between the natural shows or opt-in to the natural show for bulbs that are off. Does LEAP and/or this project have support for following natural shows? Ideally, I'd be able to set the "temperature" to a natural show curve.

**Comment by cbw** [comment]
Hi @kneath, unfortunately without a full spec on LEAP, we're a bit limited. I'm not aware of how to command Ketra loads into a natural show. Is this something you could implement as a homeowner keypad button and then call that from HA? Obviously doesn't solve the issue of controlling an individual load through HA's UI.

I don't have Ketra fixtures (only Ketra bulbs in socketed fixtures) so I don't have the Natural Show set up in my system. I'm curious, are you able to do what you're looking for within Lutron's app natively?

I know on my Ketra bulbs I can switch between manually setting the color temp, or warm dim (color temp is automatically set based on intensity). Do you have the option in the app to set individual loads into Natural Show? All the examples I've seen of it were with keypad buttons.

**Comment by kneath** [comment]
That's kind of what I suspected. Natural Shows are kind of a weird thing, they are in the settings of the Lutron App as named entities, and don't appear anywhere on the device screens. I think the only place the connection between the named natural show and the scene is in Designer itself. 

I believe I can go with the homeowner keypad variation, it's just a bummer to have to have to involve my rep every time for things like this since QSX won't allow me to create my own buttons. And to suffer the Lutron app to design the lighting. HA is 100x more pleasant to deal with.

**Comment by cbw** [comment]
I feel ya there – my approach was I had my installer create a whole ton of Homeowner Keypads assigned to the equipment room, that way I had a whole slew of buttons I could use for various things without having to call them. This was helpful for things like controlling a group of shades (I was afraid HA sending open/close commands to a bunch of independent shades at once would lead to "waterfall" across banks of windows).

(btw hope you don't mind, checked out your profile, and the house you built is stunning! Recently finished a massive renovation, can totally appreciate all the thought that went into everything)

**Comment by kneath** [comment]
Thank you! I still need to write more about it, especially now that we're all finished. I like your idea, I guess I didn't realize I can rename the button names if they're a homeowner keypad and not a palladiom keypad. I'm still learning the nuances of what I can actually change and what I can't…

**Comment by cbw** [comment]
I spent a lot of time figuring out how I wanted them to program my system to minimize service calls for config changes. I also wanted to hedge against anything going sideways with HA or the integration in the future, so one of my principles is to keep as much lighting config in QSX as possible, and just command it with virtual button presses.

Since it can get tricky with how you can edit certain button types as a customer, I had them create all my scenes as area scenes, and then assign them to buttons (e.g., my kitchen has a 4-button Palladiom with the buttons "Kitchen", "Prepare," "Entertain", and "Relax." There are actually 6 scenes behind it – single-tap on "Kitchen" activates "normal" (as a toggle-action, if any light in the area is on, tapping again will turn it off) and a double-tap is "Bright", "Prepare" and "Entertain" are regular single-action for those scenes, single-tap on "Relax" is the "relax" scene, and a double-tap is a "dimmed" scene.

One of my homeowner keypads is "Kitchen" and has direct, single-action buttons for each of those area scenes:

![image](https://github.com/user-attachments/assets/ce42d2b4-9143-44c8-b307-5df8be1ba853)

That allows me both directly edit those scenes through the homeowner app (otherwise I couldn't edit the scenes behind the double-tap), as well as to directly activate those scenes in a very deterministic way (as well as getting status from the LEDs).

For example, I have an automation in HA that activates the "relax" scene in every room before sunset, but only if the room is off (so if I'm cooking in the kitchen, don't turn the lights down on me). Since I can read the LED state of "Room Off" I'm guaranteed to know its current state without having to look at a whole list of lighting loads.

In addition, I had some generic utility homeowner keypads created, where I can have scenes like "Dining Room Shades Open" and "Dining Room Shades Close" so I can trigger all those shades at once from HA without potential of waterfalling if there's any latency between LEAP commands.

I think the only thing I've had to go back to my installer for is when I've moved lamps with Ketra bulbs between rooms and wanted that updated, and I need to get them back out to tweak some shade trims since you can't do that in the app yourself.

Hope this helps!

**Comment by kneath** [comment]
Thanks! I like that strategy. One of the hangups I've had is I can't edit "Shared Scenes" — whenever there's more than one button that can trigger the same scene. And more importantly, there is no way to know what is a shared scene or a room scene in the Lutron app, and it does allow you to edit settings, but they don't apply or even get queued up in designer. I'll ask my rep to see if we can move those shared scenes to a homeowner keypad and trigger them through the buttons and still maintain state.

I also think I'm beginning to agree about keeping config in QSX as much as I hate doing everything in the Lutron app. I haven't found a way to set the state of a button through pylutron. I can change the LED, but the state is somewhere hidden, which results in buttons needing two or three presses to get back to a good state if I change the blinds remotely.

**Comment by cbw** [comment]
Yeah, shared scenes are a homeowner's nightmare! If you shift everything to area scenes, you can then assign them to both physical buttons (including behind double-tap) as well as homeowner keypad buttons and have full editing control. There's not a single scene in my system I can't edit myself.

I think your issue around button state is there isn't a button state, per se. Buttons _can_ and usually _do_ impact some other state in the system (and their LEDs usually reflect that underlying state), but the button itself is arguably stateless.

My approach of having HA only press buttons on homeowner keypads gives me a very consistent, idempotent way of setting the state to what I want. By using single-action buttons on those homeowner keypads allows me to use their LEDs to read the state of the actual system (e.g., if the "normal" button LED on the kitchen homeowner keypad is lit, I know that that zone is on its "normal" scene, versus reading the "kitchen" button on the physical keypad just tells me at least one load in that area is on).

At least for me, I went through a period of a couple months where I was constantly tweaking my scenes in the Lutron app, but I've almost never touched it since then.

**Comment by Paul-at-home** [comment]
Vibrancy was not implemented. Fairly easy to add it to set_value in smartbridge.py. Sorry I do not know how to submit my changes for review.
